### PR TITLE
Add basic hyprcursor theme support

### PR DESCRIPTION
**Pull request by greentea-cup**
I like this theme and would like to contribute to it by adding support for Hyprland's hyprcursor theme format. Here are build and install scripts that create hyprcursor theme from source files and installs into specified directory or a default one (it uses svg as opposed to decompressing built xcursor theme and using png, installs by default into `$HOME/.local/share/icons/`).

Edit: prebuilt hyprcursor theme sources and end-user themes are also provided.

### CODE REVIEW

**Comment by SueDonham** [comment]
Very cool, thanks! First I've heard of hyprcursor.

I'm thinking a good way to incorporate this would be updating the icon install script so that if a user wants cursors, they're asked which format (which cursor's install script to call). Something like:

```
# Prompt to install cursors:
read -p "Install cursor theme? [y|N] " YN
if [[ "$YN" == [yY]* ]]; then
	cd $CURSOR_DIR
	read -p $'XCursor or hyprcursor?\n1) XCursor\n2) hyprcursor\nEnter selection [1|2]: ' format
	case $format in
		1) bash $CURSOR_DIR/install-xc.sh ;;
		2) bash $CURSOR_DIR/install-hl.sh ;;
		*) echo "Invalid selection; run cursors/install-xc.sh for Xcursor or cursors/install-hl.sh for Hyprcursor" ;;
	esac
fi
```
Let me know if you can spot anything dumb about this idea (I'm extremely green).

**Comment by greentea-cup** [comment]
Just realised there are some places that need fixes in my pr.
Universal script that splits to 2 options sounds like a good idea, I could only think of both options at the same time.

**Comment by greentea-cup** [comment]
Looks like I missed some updates. Initially I planned to do some changes to pr but since I was lazy enough to not do anything related to any project during the last month, I was surprised to see this being merged and instantly reverted.
Could you please explain to me if you are still waiting for changes or was this revert done for the reasons unknown to me?

**Comment by SueDonham** [comment]
The revert was because the merge was an accident (premature--did not mean to merge in the code you aren't happy with). Unfortunately, I can't seem to find a way to reopen a PR that was merged, so hopefully it's not too much trouble to open a new one whenever you're ready to. Sorry for the confusion; I wasn't joking when I said I was new to this!

**Comment by greentea-cup** [comment]
Thanks for the clarification and fast answer (unlike me).
I will rework script and make new pr in a week or so.

**Pull request merged**
